// Generated by https://quicktype.io

export interface CompanySize {
  companySize: CompanySizeElement[];
}

export interface CompanySizeElement {
  ID_TAMANO_EMPRESA: number;
  TAMANO_EMPRESA:    string;
}
