// Generated by https://quicktype.io

export interface NormalStudent {
  DBStudent:        DBStudent;
  DBStudentDetails: DBStudentDetails;
  ok:               boolean;
  msg:              string;
}

export interface DBStudent {
  CORREO_ELECTRONICO: string;
  CONTRASENA:         string;
}

export interface DBStudentDetails {
  NOMBRE_USUARIO:        string;
  NOMBRE:                string;
  APELLIDO:              string;
}
