// Generated by https://quicktype.io

export interface PYMEStudent {
  DBStudent:     DBStudent;
  DBPYMEDetails: DBPYMEDetails;
  ok:            boolean;
  msg:           string;
}

export interface DBPYMEDetails {
  NOMBRE_USUARIO:    string;
  TELEFONO:          string;
  NOMBRE_EMPRESA:    string;
  ID_TAMANO_EMPRESA: number;
  ID_UBICACION:      number;
}

export interface DBStudent {
  CORREO_ELECTRONICO: string;
  CONTRASENA:         string;
}
