// Generated by https://quicktype.io

export interface ResponseCreatePYME {
  User:          User;
  DBPYMEDetails: DBPYMEDetails;
  ok:            boolean;
  msg:           string;
}

export interface DBPYMEDetails {
  ID_DETALLE_PYME:   null;
  ID_USUARIO:        number;
  TELEFONO:          string;
  NOMBRE_EMPRESA:    string;
  ID_TAMANO_EMPRESA: number;
  ID_UBICACION:      number;
}

export interface User {
  ID_USUARIO:         null;
  USUARIO:            string;
  NOMBRE_USUARIO:     string;
  CORREO_ELECTRONICO: string;
  ID_ROL:             number;
  ESTADO_USUARIO:     string;
  CONTRASENA:         string;
  FECHA_MODIFICACION: string;
  FECHA_CREACION:     string;
}
